name: Sync Branches

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request to Sync Branches
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          commit-message: 'Sync branch with main'
          title: 'Sync branch with main'
          body: 'This PR automatically updates this branch to match the latest changes in the main branch.'
          base: main
          labels: 'sync'
          add-paths: '["*"]'